import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import React, { useEffect, useState } from "react";

import ChatContent from "../../components/ChatContent";
import Groups from "../../components/Groups";
import ServerToolBar from "../../components/ServerToolBar";
import { firestore } from "../../firebase/firebase";

type ChatScreenProps = {};

const ChatScreen: React.FC<ChatScreenProps> = () => {
  const [cardData, setCardData] = useState<any[]>([]);

  useEffect(
    () =>
      onSnapshot(
        query(collection(firestore, "discord"), orderBy("timestamp", "desc")),
        (snapshot) => {
          setCardData(snapshot.docs);
        }
      ),
    [firestore]
  );

  return (
    <div className="flex bg-[#393943] overflow-hidden h-screen">
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.bing.com/th?id=ALSTU247930B68ED76C8F08617E6559DE8E3B96BC0F73153C44DED6DCD678C245494B&w=148&h=148&c=7&o=6&oif=webp&dpr=1.3&pid=SANGAM"
        />
      </Head>
      <Groups />
      <ServerToolBar />
      {cardData.map((data) => (
        <ChatContent key={data.id} docIds={data.id} />
      ))}
    </div>
  );
};
export default ChatScreen;
