import React, { useEffect } from "react";
import Head from "next/head";

import LoginHeader from "../../components/LoginHeader";
import Sign from "../../components/Sign";
import { useRouter } from "next/router";
import { useAuthState, useSignInWithGoogle } from "react-firebase-hooks/auth";
import { auth } from "../../firebase/firebase";

type SigninProps = {};

const Signin: React.FC<SigninProps> = () => {
  const [user] = useAuthState(auth);
  const router = useRouter();
  const [signInWithGoogle, userCred, loading, error] =
    useSignInWithGoogle(auth);

  useEffect(() => {
    if (user) {
      router.push("/");
    } else return;
  }, [user]);

  return (
    <div>
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://th.bing.com/th/id/R.d248fb5cf17f6dd4d50a0ec816e3d1fa?rik=JZcf3Y7HNivrdw&pid=ImgRaw&r=0"
        />
      </Head>
      <LoginHeader signInWithGoogle={signInWithGoogle} />
      <Sign signInWithGoogle={signInWithGoogle} />
    </div>
  );
};
export default Signin;
