import { motion } from "framer-motion";
import Head from "next/head";
import React from "react";

import LoginHeader from "../../components/LoginHeader";
import Sign from "../../components/Sign";

type SigninProps = {};

const Signin: React.FC<SigninProps> = () => {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://th.bing.com/th/id/R.d248fb5cf17f6dd4d50a0ec816e3d1fa?rik=JZcf3Y7HNivrdw&pid=ImgRaw&r=0"
        />
      </Head>
      <LoginHeader />
      <Sign />
    </motion.div>
  );
};
export default Signin;
