import React from "react";
import Head from "next/head";
import { useSession } from "next-auth/react";

import Groups from "../../components/Groups";
import Discover from "../../components/Discover";
import CreateServer from "../../components/Community/CreateServer";
import MainSign from "../../components/MainSign";

type CreateCommunityProps = {};

const CreateCommunity: React.FC<CreateCommunityProps> = () => {
  const { data: session } = useSession();
  if (!session) return <MainSign />;

  return (
    <div className="flex bg-[#393943]">
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.bing.com/th?id=ALSTU247930B68ED76C8F08617E6559DE8E3B96BC0F73153C44DED6DCD678C245494B&w=148&h=148&c=7&o=6&oif=webp&dpr=1.3&pid=SANGAM"
        />
      </Head>
      <Groups />
      <Discover />
      <div className="h-full w-full overflow-y-scrool scrollbar-hide">
        <CreateServer />
      </div>
    </div>
  );
};
export default CreateCommunity;
